// @COPYRIGHT@
// Licensed under MIT license (LICENSE.txt)

/** // doc: clxx/info/platform_info_ptr.li.swg {{{
 * \file clxx/info/platform_info_ptr.li.swg
 * \todo Write documentation
 */ // }}}

%{
#include <clxx/info/platform_info_ptr.hpp>
%}

%include <clxx/common/shared_ptr.swg>
CLXX_DECL_CLASS_SHARED_PTR1(clxx, platform_info)

// vim: set expandtab tabstop=2 shiftwidth=2:
// vim: set foldmethod=marker foldcolumn=4:
