
# @COPYRIGHT@
# Licensed under MIT license (LICENSE.txt).

Import('env')

from SCons.Util import CLVar

libs = CLVar('clxx_app_clcc')
clcc = env.Program('clxx-clcc', 'main.cpp', LIBS = libs)

ibin = env.Install('${bindir}', clcc)
env.Ignore("${INSTALL_SANDBOX}${bindir}", ibin)

env.Alias('install-app-clcc', ibin)
env.Alias('install','install-app-clcc')

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
