// @COPYRIGHT@
// Licensed under MIT license (LICENSE.txt)

/** // doc: clxx/util/std_except_ctor_arg.li.swg {{{
 * \file clxx/util/std_except_ctor_arg.li.swg
 * \todo Write documentation
 */ // }}}

%{
#include <clxx/util/std_except_ctor_arg.hpp>
%}
%include <clxx/util/std_except_ctor_arg_fwd.hpp>
%include <clxx/util/std_except_ctor_arg.hpp>

// vim: set expandtab tabstop=2 shiftwidth=2:
// vim: set foldmethod=marker foldcolumn=4:
