
# @COPYRIGHT@
# Licensed under MIT license (LICENSE.txt).

Import('env')

from SCons.Util import CLVar

libs = CLVar('clxx_app_clinfo')
clinfo = env.Program('clxx-clinfo', 'main.cpp', LIBS = libs)

ibin = env.Install('${bindir}', clinfo)
env.Ignore("${INSTALL_SANDBOX}${bindir}", ibin)

env.Alias('install-app-clinfo', ibin)
env.Alias('install','install-app-clinfo')

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
