// @COPYRIGHT@
// Licensed under MIT license (LICENSE.txt)

/** // doc: clxx/common/ndrange.swg {{{
 * \file clxx/common/ndrange.swg
 * \todo Write documentation
 */ // }}}

%ignore clxx::ndrange::global_offset_ptr;
%ignore clxx::ndrange::global_size_ptr;
%ignore clxx::ndrange::local_size_ptr;
%include <clxx/common/ndrange.li.swg>

// vim: set expandtab tabstop=2 shiftwidth=2:
// vim: set foldmethod=marker foldcolumn=4:
