// @COPYRIGHT@
// Licensed under MIT license (LICENSE.txt)

/** // doc: clxx/context_property.li.swg {{{
 * \file clxx/context_property.li.swg
 * \todo Write documentation
 */ // }}}

%{
#include <clxx/context_property.hpp>
%}

// The clxx::context_property class has only noexcept methods, there is no
// exceptions to specify.

%include <clxx/context_property.hpp>

// vim: set expandtab tabstop=2 shiftwidth=2:
// vim: set foldmethod=marker foldcolumn=4:
