// @COPYRIGHT@
// Licensed under MIT license (LICENSE.txt)

/** // doc: clxx/platform_query.li.swg {{{
 * \file clxx/platform_query.li.swg
 * \todo Write documentation
 */ // }}}

%{
#include <clxx/platform_query.hpp>
%}

// The clxx::device_query class has only noexcept methods. There is no need for
// specifying exceptions.

%include <clxx/platform_query.hpp>

// vim: set expandtab tabstop=2 shiftwidth=2:
// vim: set foldmethod=marker foldcolumn=4:
