// @COPYRIGHT@
// Licensed under MIT license (LICENSE.txt)

/** // doc: clxx/program_sources.li.swg {{{
 * \file clxx/program_sources.li.swg
 * \todo Write documentation
 */ // }}}

%include <clxx/program_source.swg>
%{
#include <clxx/program_sources.hpp>
%}
%template() std::vector<clxx::program_source>;
%include <clxx/program_sources.hpp>

// vim: set expandtab tabstop=2 shiftwidth=2:
// vim: set foldmethod=marker foldcolumn=4:
