
# @COPYRIGHT@
# Licensed under MIT license (LICENSE.txt).

Import(['env'])

from SCons.Util import CLVar

env.Program('exception1.cpp')
env.Program('exception2.cpp')
env.Program('exception3.cpp')
env.Program('exception4.cpp')
env.Program('autosep1.cpp', LIBS = CLVar('clxx_io'))
env.Program('io1.cpp', LIBS = CLVar('clxx_io'))
env.Program('platform1.cpp', LIBS = CLVar('clxx_cl'))
env.Program('platform2.cpp', LIBS = CLVar('clxx_cl clxx_info clxx_io'))
env.Program('platform3.cpp', LIBS = CLVar('clxx_cl clxx_info clxx_io'))
env.Program('platform4.cpp', LIBS = CLVar('clxx_cl clxx_info clxx_io'))
env.Program('device1.cpp', LIBS = CLVar('clxx_cl'))

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
