
# @COPYRIGHT@
# Licensed under MIT license (LICENSE.txt).

Import(['env'])

from SCons.Util import CLVar

env.Program('exception1.cpp')
env.Program('exception2.cpp')
env.Program('exception3.cpp')
env.Program('exception4.cpp')
env.Program('autosep1.cpp', LIBS = CLVar('clxx_io'))
env.Program('io1.cpp', LIBS = CLVar('clxx_io'))
env.Program('platform1.cpp', LIBS = CLVar('clxx_cl'))
env.Program('platform2.cpp', LIBS = CLVar('clxx_cl clxx_info clxx_io'))
env.Program('platform3.cpp', LIBS = CLVar('clxx_cl clxx_info clxx_io'))
env.Program('platform4.cpp', LIBS = CLVar('clxx_cl clxx_info clxx_io'))
env.Program('device1.cpp', LIBS = CLVar('clxx_cl'))
env.Program('device_info1.cpp', LIBS = CLVar('clxx_info clxx_io'))
env.Program('platform_info1.cpp', LIBS = CLVar('clxx_info clxx_io'))
env.Program('query_platform_info1.cpp', LIBS = CLVar('clxx_info clxx_io clxx_cl'))
env.Program('query_device_info1.cpp', LIBS = CLVar('clxx_info clxx_io clxx_cl'))
env.Program('query_platform_layer_info1.cpp', LIBS = CLVar('clxx_info clxx_io clxx_cl'))
env.Program('mem1.cpp', LIBS = CLVar('clxx_cl clxx_io'))
env.Program('s11n1.cpp', LIBS = CLVar('clxx_cl clxx_info clxx_s11n boost_serialization'))
env.Program('s11n2.cpp', LIBS = CLVar('clxx_info clxx_s11n clxx_io boost_serialization'))
env.Program('cl/program_generator1.cpp', LIBS = CLVar('clxx_cl clxx_io'))
env.Program('cl/kernel_lazy_constructor1.cpp', LIBS = CLVar('clxx_cl'))
env.Program('common/memoized_function1.cpp', LIBS = CLVar())

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
