
# @COPYRIGHT@
# Licensed under MIT license (LICENSE.txt).

Import(['env'])

env['CLXX_PACKAGES'] = {}

SConscript('SConscript.tools', exports = ['env'])
SConscript('SConscript.defaults', exports = ['env'])
SConscript('SConscript.cli', exports = ['env'])
SConscript('SConscript.adjust', exports = ['env'])
if not env.GetOption('clean') and not env.GetOption('help') \
   and not env.GetOption('help_variables'):
   conf = env.Configure(conf_dir = '.sconf_temp', log_file = 'config.log',
                        config_h = 'lib/clxx/config.h')
   SConscript('SConscript.conf', exports = ['conf'])
   env = conf.Finish()
SConscript('SConscript.adjust2', exports = ['env'])

SConscript('lib/SConscript', exports = ['env'])
SConscript('examples/SConscript', exports = ['env'])
SConscript('doc/SConscript', exports = ['env'])
SConscript('test/SConscript', exports = ['env'])
SConscript('app/SConscript', exports = ['env'])

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
