// @COPYRIGHT@
// Licensed under MIT license (LICENSE.txt)

/** // doc: clxx/common/clerror_base.li.swg {{{
 * \file clxx/common/clerror_base.li.swg
 * \todo Write documentation
 */ // }}}

%include <clxx/common/clerror.swg>
%include <clxx/common/clerror_stdexcept.hpp>
%{
#include <clxx/common/clerror_base.hpp>
%}
%include <clxx/common/clerror_base.hpp>

// vim: set expandtab tabstop=2 shiftwidth=2:
// vim: set foldmethod=marker foldcolumn=4:
