// @COPYRIGHT@
// Licensed under MIT license (LICENSE.txt)

/** // doc: clxx/common/context_property_type.li.swg {{{
 * \file clxx/common/context_property_type.li.swg
 * \todo Write documentation
 */ // }}}

%{
#include <clxx/common/context_property_type.hpp>
%}
%include <clxx/common/context_property_type_fwd.hpp>
%include <clxx/common/context_property_type.hpp>

// vim: set expandtab tabstop=2 shiftwidth=2:
// vim: set foldmethod=marker foldcolumn=4:
