// @COPYRIGHT@
// Licensed under MIT license (LICENSE.txt)

/** // doc: clxx/common/ndrange.li.swg {{{
 * \file clxx/common/ndrange.li.swg
 * \todo Write documentation
 */ // }}}

%{
#include <clxx/common/ndrange.hpp>
%}

%include <stdint.i>
%include <std_vector.i>
%template() std::vector<size_t>;

%include <clxx/common/ndrange.hpp>

// vim: set expandtab tabstop=2 shiftwidth=2:
// vim: set foldmethod=marker foldcolumn=4:
